# -*- coding: utf-8 -*-
"""project_Tiny_GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzm0cA3XZ0Of3rBNLguG2d5pAQKS7dqp

### Tiny GPT
##### What We're Building
      You feed it:     a big pile of text
      It learns:       "what letter usually comes next?"
      Then it WRITES:  brand new text, one letter at a time

##### 1. Get the Data
"""

import torch
import torch.nn as nn
import math
import urllib.request

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Download Shakespeare (about 1MB, free)
url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
urllib.request.urlretrieve(url, "shakespeare.txt")

with open("shakespeare.txt", "r") as f:
    text = f.read()

print("Total characters:", len(text))
print("\n--- First 300 characters ---")
print(text[:300])

"""##### 2. Build the character vocabulary (Data Preprocessing)"""

# Find every unique character in the text
characters = sorted(set(text))
VOCAB_SIZE = len(characters)

print("Vocabulary size:", VOCAB_SIZE)
print("The characters:", "".join(characters))

# Two dictionaries: character → number, and number → character
char_to_number = {ch: i for i, ch in enumerate(characters)}
number_to_char = {i: ch for i, ch in enumerate(characters)}

print(char_to_number)

# Two helper functions
def encode(s):
    return [char_to_number[c] for c in s]

def decode(numbers):
    return "".join([number_to_char[n] for n in numbers])

# Test them!
print("\nencode('hello'):", encode("hello"))
print("decode it back: ", decode(encode("hello")))

# Turn the WHOLE text into one long list of numbers
data = torch.tensor(encode(text), dtype=torch.long)
print("\ndata shape:", data.shape)
print("first 20 numbers:", data[:20].tolist())
print("decoded back:    ", repr(decode(data[:20].tolist())))

"""##### 3. Cut the chunks"""

CHUNK_SIZE = 128      # how many characters the model sees at once
BATCH_SIZE = 32       # how many chunks we process together

# Split: 90% for training, 10% for checking
split_point = int(0.9 * len(data))
train_data = data[:split_point]
val_data   = data[split_point:]

print("train characters:", len(train_data))
print("val characters:  ", len(val_data))


def get_batch(which_split):
    d = train_data if which_split == "train" else val_data

    # pick BATCH_SIZE random starting points
    # torch.randint(0-high, (size,))
    starts = torch.randint(len(d) - CHUNK_SIZE - 1, (BATCH_SIZE,))
    print(starts)

    x = torch.stack([d[s     : s + CHUNK_SIZE    ] for s in starts])   # the chunk
    y = torch.stack([d[s + 1 : s + CHUNK_SIZE + 1] for s in starts])   # shifted by 1!

    return x.to(device), y.to(device)


x, y = get_batch("train")
print(f"\n x:- {x}")
print(f"\n y:- {y}")
print("\nx shape:", x.shape)
print("y shape:", y.shape)

# A small demo so we can actually read it
demo_start = 100
demo_x = train_data[demo_start     : demo_start + 8]
demo_y = train_data[demo_start + 1 : demo_start + 9]

print("x numbers:", demo_x.tolist())
print("y numbers:", demo_y.tolist())
print("x text:", repr(decode(demo_x.tolist())))
print("y text:", repr(decode(demo_y.tolist())))

print("\n--- The 8 lessons hidden in this ONE chunk ---")
for i in range(8):
    context = decode(demo_x[:i+1].tolist())
    answer  = number_to_char[demo_y[i].item()]
    print(f"  saw {repr(context):<14} → predict {repr(answer)}")

"""##### 4. The Model"""

NUMBERS_PER_CHAR  = 128     # d_model — how many numbers describe each character
NUMBER_OF_HEADS   = 4       # so each head gets 128 ÷ 4 = 32
NUMBER_OF_BLOCKS  = 4       # how many transformer blocks stacked


class MultiHeadAttention(nn.Module):
    def __init__(self, numbers_per_char, number_of_heads):
        super().__init__()
        self.number_of_heads  = number_of_heads
        self.numbers_per_head = numbers_per_char // number_of_heads

        self.W_query  = nn.Linear(numbers_per_char, numbers_per_char)
        self.W_key    = nn.Linear(numbers_per_char, numbers_per_char)
        self.W_value  = nn.Linear(numbers_per_char, numbers_per_char)
        self.W_output = nn.Linear(numbers_per_char, numbers_per_char)

    def forward(self, x, mask):
        batch, chars, numbers = x.shape
        H, P = self.number_of_heads, self.numbers_per_head

        q = self.W_query(x).view(batch, chars, H, P).transpose(1, 2)
        k = self.W_key(x).view(batch, chars, H, P).transpose(1, 2)
        v = self.W_value(x).view(batch, chars, H, P).transpose(1, 2)

        scores = (q @ k.transpose(-2, -1)) / math.sqrt(P)    # score + scale
        scores = scores + mask                                # BLOCK the future 🙈
        look_percent = torch.softmax(scores, dim=-1)          # → percentages

        heads  = look_percent @ v                             # blend the values
        joined = heads.transpose(1, 2).reshape(batch, chars, numbers)
        return self.W_output(joined)                          # mix the heads


class TransformerBlock(nn.Module):
    def __init__(self, numbers_per_char, number_of_heads):
        super().__init__()
        self.attention = MultiHeadAttention(numbers_per_char, number_of_heads)
        self.norm_1 = nn.LayerNorm(numbers_per_char)
        self.feed_forward = nn.Sequential(
            nn.Linear(numbers_per_char, numbers_per_char * 4),   # EXPAND 128 → 512
            nn.ReLU(),                                            # switch some off
            nn.Linear(numbers_per_char * 4, numbers_per_char),   # SQUEEZE 512 → 128
            nn.Dropout(0.1),                                      # anti-overfitting
        )
        self.norm_2 = nn.LayerNorm(numbers_per_char)

    def forward(self, x, mask):
        x = self.norm_1(x + self.attention(x, mask))       # ADD & NORM
        x = self.norm_2(x + self.feed_forward(x))          # ADD & NORM
        return x


class TinyGPT(nn.Module):
    def __init__(self, vocab_size, numbers_per_char, number_of_heads,
                 number_of_blocks, chunk_size):
        super().__init__()
        self.char_table     = nn.Embedding(vocab_size, numbers_per_char)
        self.position_table = nn.Embedding(chunk_size, numbers_per_char)
        self.blocks = nn.ModuleList([
            TransformerBlock(numbers_per_char, number_of_heads)
            for _ in range(number_of_blocks)
        ])
        self.final_norm  = nn.LayerNorm(numbers_per_char)
        self.char_scorer = nn.Linear(numbers_per_char, vocab_size)

    def forward(self, chunk):
        batch, how_many_chars = chunk.shape

        positions = torch.arange(how_many_chars, device=chunk.device)
        x = self.char_table(chunk) + self.position_table(positions)   # ADD position!

        mask = torch.triu(
            torch.full((how_many_chars, how_many_chars), float('-inf'), device=chunk.device),
            diagonal=1)                                                # the staircase 📶

        for block in self.blocks:
            x = block(x, mask)

        x = self.final_norm(x)
        return self.char_scorer(x)


model = TinyGPT(VOCAB_SIZE, NUMBERS_PER_CHAR, NUMBER_OF_HEADS,
                NUMBER_OF_BLOCKS, CHUNK_SIZE).to(device)

total = sum(p.numel() for p in model.parameters())
print(f"Total settings: {total:,}")

# Test it
scores = model(x)
print("\nx shape (input):     ", x.shape)
print("scores shape (output):", scores.shape)

LEARNING_RATE = 0.003
TRAINING_STEPS = 3000

loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)


@torch.no_grad()
def check_loss():
    """Measure loss on both train and val, without training."""
    model.eval()
    results = {}
    for split in ["train", "val"]:
        total = 0.0
        for _ in range(20):                      # average over 20 batches
            xb, yb = get_batch(split)
            scores = model(xb)
            loss = loss_function(scores.reshape(-1, VOCAB_SIZE), yb.reshape(-1))
            total += loss.item()
        results[split] = total / 20
    model.train()
    return results


print("Starting loss (before any training):", check_loss())
print("Random guessing would be:", round(math.log(VOCAB_SIZE), 4))
print()

for step in range(TRAINING_STEPS):
    xb, yb = get_batch("train")

    optimizer.zero_grad()
    scores = model(xb)                                          # (32, 128, 65)

    flat_scores  = scores.reshape(-1, VOCAB_SIZE)               # (4096, 65)
    flat_targets = yb.reshape(-1)                               # (4096,)

    loss = loss_function(flat_scores, flat_targets)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
    optimizer.step()

    if step % 500 == 0 or step == TRAINING_STEPS - 1:
        losses = check_loss()
        print(f"step {step:>4} | train {losses['train']:.4f} | val {losses['val']:.4f}")

print("\nTraining complete! 🎉")

@torch.no_grad()
def generate(model, how_many_new=500, temperature=1.0, starting_text="\n"):
    model.eval()

    chunk = torch.tensor([encode(starting_text)], dtype=torch.long, device=device)

    for _ in range(how_many_new):
        # only feed the last CHUNK_SIZE characters (that's all it can see)
        chunk_cropped = chunk[:, -CHUNK_SIZE:]

        scores = model(chunk_cropped)             # (1, chars, 65)
        last_scores = scores[0, -1]               # ⭐ only the LAST position!

        last_scores = last_scores / temperature   # ⭐ the Module 9 knob! 🌡️
        probabilities = torch.softmax(last_scores, dim=0)

        next_char = torch.multinomial(probabilities, num_samples=1)  # sample!
        chunk = torch.cat([chunk, next_char.unsqueeze(0)], dim=1)    # glue it on

    return decode(chunk[0].tolist())


print("=" * 60)
print("TEMPERATURE 0.5 (careful, repetitive)")
print("=" * 60)
print(generate(model, 400, temperature=0.5))

print("\n" + "=" * 60)
print("TEMPERATURE 1.0 (balanced)")
print("=" * 60)
print(generate(model, 400, temperature=1.0))

print("\n" + "=" * 60)
print("TEMPERATURE 1.5 (wild, creative)")
print("=" * 60)
print(generate(model, 400, temperature=1.5))

